// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzP68ED2bLPIzfP91hfWpHB47_QuoXdhU',
    appId: '1:1074329593439:web:8f04f7c8179b497f38ddea',
    messagingSenderId: '1074329593439',
    projectId: 'qr-code-e845f',
    authDomain: 'qr-code-e845f.firebaseapp.com',
    storageBucket: 'qr-code-e845f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOWNTmtVsHO0YY1vPoW_n41bX-kpoMw4',
    appId: '1:1074329593439:android:e76010dd35b42aa238ddea',
    messagingSenderId: '1074329593439',
    projectId: 'qr-code-e845f',
    storageBucket: 'qr-code-e845f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0m9cGzrW8iOO-xXMg2jXWyDPaP5nmLn0',
    appId: '1:1074329593439:ios:1d5cd5ccdf6dc43a38ddea',
    messagingSenderId: '1074329593439',
    projectId: 'qr-code-e845f',
    storageBucket: 'qr-code-e845f.appspot.com',
    iosClientId: '1074329593439-8ulkph5fqg7jrfacg7b04eun9s8kh82u.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0m9cGzrW8iOO-xXMg2jXWyDPaP5nmLn0',
    appId: '1:1074329593439:ios:1d5cd5ccdf6dc43a38ddea',
    messagingSenderId: '1074329593439',
    projectId: 'qr-code-e845f',
    storageBucket: 'qr-code-e845f.appspot.com',
    iosClientId: '1074329593439-8ulkph5fqg7jrfacg7b04eun9s8kh82u.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );
}
